README.md

I spotted a few minor tweaks that I wanted to make to the README.

Spruce up README.md

---

pyproject.toml

I changed Recap's slogan but forgot to update pyproject.toml. I'm fixing that now.

Update Recaps pyproject.toml description

---

recap/crawler.py
recap/logging.py
recap/plugins/analyzers/abstract.py
recap/plugins/browsers/abstract.py
recap/plugins/browsers/db.py
recap/plugins/catalogs/abstract.py
recap/plugins/catalogs/recap.py
recap/plugins/commands/catalog.py
recap/plugins/commands/crawl.py
recap/plugins/commands/plugins.py
recap/plugins/commands/serve.py

I took a pass at docstrings for the main classes in Recap. It's pretty cursory, but hopefully it's enough to start people off.
Closes #3

Add docstrings

---

pyproject.toml

I'm getting ready to publish 0.2.1 because I want to get #75 out since it's causing install problems.

Bump to version 0.2.1

---

recap/analyzers/db/access.py
recap/analyzers/db/foreign_key.py
recap/analyzers/db/index.py
recap/analyzers/db/primary_key.py
recap/browsers/abstract.py
recap/browsers/db.py
recap/catalogs/abstract.py
recap/catalogs/db.py
recap/catalogs/recap.py
recap/commands/crawl.py
recap/crawler.py
recap/routers/directory.py
recap/routers/search.py

Since I committed to Python 3.10 in #88, I decided to clean up the unnecessary `from typing import List` imports.

Replace `List[]` with `list[]`

---

recap/commands/crawl.py
recap/crawler.py

This is a minor tweak to get the crawler.open method looking the same way as the other open methods which are now `create_*` after last commit.

Use `create_crawler` in `recap.crawler`

---

docs/browsers.md
docs/plugins.md
docs/server.md
pyproject.toml
recap/catalogs/db.py

Update REST API docs

---

docs/index.md
docs/quickstart.md
recap/browsers/db.py
recap/commands/crawl.py

Add Python examples to Quickstart

---

pyproject.toml

0.4.1 has been pushed, so bumping before more features are added.

Bump version to 0.4.2

---

DEVELOPER.md
pyproject.toml
recap/analyzers/duckdb/columns.py
recap/analyzers/frictionless/columns.py
recap/analyzers/genson/columns.py
recap/analyzers/pandas/profile.py
recap/browsers/db.py
recap/plugins.py
recap/typing.py

Adding pyright in the CI exposed a few errors. It looks like they were all the result of black reformatting things incorrectly. I've fixed them and made a couple of grammar tweaks in the DEVELOPER.md.

Fix pyright type hint errors

---

pdm.lock
pyproject.toml

It looks like I lost `tomli` during the rewrite. Re-adding.

Re-add `tomli`

---

README.md
docs/api/recap.metadata.md
docs/api/recap.schema.md
docs/index.md
mkdocs.yml
pyproject.toml

Time to start showcasing what Recap can do with schemas.

Update README.md and index.md to show more `schema()` examples

---

recap/schema/converters/avro.py
recap/schema/converters/json_schema.py
recap/schema/types.py

In my rush to merge things in, I didn't let the CI pass. I missed some styling. I'm fixing that.
More embarassingly, I missed some JSON schema converter bugs. I'm fixing that as well.

Fix styling

---

SPEC.md

Some small fixes. What's the best way for commenting on the doc itself? I have a few questions/thoughts here and there, but not sure where to put them.

Typo fixes for SPEC.md

---

SPEC.md
recap/schema/types.py

I added a bit more of an intro and clarified a few points in the spec based on feedback.

Update intro and clarification in SPEC

---

SPEC.md

I've added a bunch of documentation to the type spec and also used markdown tables for attributes.

Add more documentation to the Recap type spec

---

recap/__init__.py
recap/catalog/server.py
recap/models.py

I took a crack at adding the `diff` command to the REST API. Not super thrilled with how it turned out (especially the `join` stuff). I'm going to try and clean things up a bit as a separate PR.

Add `diff` to the REST API

---

SPEC.md

I'm pulling logical types out of aliases. They are two different things and should be treated as such. Combinging them was confusing. There is now an optional `"logical"` field for all Recap types.
I took the opportunity to make a few other minor tweaks to the spec as well.
* Add an optional `name` to structs.
* Fix some typos

Update spec to differentiate between aliases and logical types

---

recap/converters/json_schema.py
recap/types.py
tests/converters/test_json_schema.py

I've added a *very* basic JSON schema converter. The converter handles the basic JSON schema types, arrays, and objects.
Closes #247

Add JSONSchemaConverter

---

recap/readers/postgresql.py
recap/readers/snowflake.py

I had a few random prints floating around. Removing them.

Remove random prints

---

README.md

Now that Recap has refocused on Python and schemas, the README needs to be updated. Making those changes in this commit.

Update README.md with code examples

---

pyproject.toml

Adding some more keywords and a better description for Recap.

Minor updates to pyproject.toml

---

tests/integration/readers/test_postgresql.py

I accidentally pushed to main and broke the `black` style lint. Fixing that.

Fix `black` styles

---

recap/converters/avro.py
tests/unit/converters/test_avro.py

`AvroConverter` can now convert `RecapType`s to Avro schemas.
The current implementation supports:
* Simple types
* Complex types
* Logical types
* Compact notation (`{"type": "string"}` -> `"string"`)
The implementation does not support:
* ProxyType
Closes #303

Add `to_avro` for `AvroConverter`

---

recap/converters/avro.py
tests/unit/converters/test_avro.py

The AvroReader had a hacky/incorrect `alias` implementation.
The new implementation now properly handles Avro's `name` and `namespace` fields. The converter uses the `name` for the Recap `extra_attrs["name"]` entry, and uses `f"{namespace}.{name}"` for the alias.

Add alias support for `to_recap` AvroReader

---

recap/converters/protobuf.py
tests/unit/converters/test_protobuf.py

Users can now convert Recap StructTypes into Protobuf Messages. This implementation returns a `proto_schem_parser.ast.File` object. If users wish to convert to a Protobuf string, they can use
`proto_schema_parser.generator.Generator` to convert the `proto_schem_parser.ast.File` object into a Protobuf schema string.
`from_recap` does the following:
1. Find all StructTypes and EnumTypes and store them as ast.Messages and ast.Enums.
2. Add all discovered messages and enums to their parents' `elements` attribute.
The implementation behaves this way because Recap allows `alias` to have an arbitrary namespace. For example:
```yaml
type: struct
alias: foo.bar.MyStruct
fields:
- name: my_field
type: struct
alias: foo.bar.MyOtherStruct
fields:
- name: my_other_field
type: string
```
This should be …

Add `ProtobufConverter.from_recap`

---

pdm.lock
pyproject.toml
tests/unit/readers/test_snowflake.py

[Fakesnow](https://github.com/tekumara/fakesnow) has had some recent patches to is precision handling. I'm upgrading to take advantage of it.

Upgrade fakesnow

---

README.md

I'm trying to get a little more crisp and approachable with Recap's README.

Update README.md with more examples and a table

---

recap/types.py
tests/unit/test_types.py

The current Recap null-field handling is a bit cumbersome. I discussed with @gwukelic, @adrianisk, and @cpard. We decided to add support for an `optional` field to the CST. This will allow us to specify that a field is optional.
See the conversation here:
https://github.com/recap-build/recap/pull/335
Users can now specify an optional field as:
```yaml
type: struct
fields:
- name: secondary_phone
type: string32
optional: true
```
This will get treated the same as:
```yaml
type: struct
fields:
- name: secondary_phone
type: "union",
types: ["null", "string32"],
default: null
```
I will update the Recap spec accordingly, as well.
Closes #335, #338

Add `optional: true` support to Recap CST

---

DEVELOPER.md

Some minor doc updates to reflect the scripts in `pyproject.toml` that were added in #353.
Closes #355

Update DEVELOPER.md with latest `pdm run test` stuff
