recap-build/recap

recap/crawlers/db/analyzers.py

The data profiler analyzer had a bug when schema and table names contained characters like hyphens. I fixed this by quoting both.

Quote table and schema in `TableDataProfileAnalyzer`

---

README.md
recap/cli.py
recap/crawlers/db/__init__.py
recap/crawlers/db/crawler.py

Users can now control which schemas and tables a crawler scans. This can done via the CLI or `settings.toml`. The CLI parameter `--filter` controls the schemas and tables to be scanned:
recap run refresh --filter='events.page_*' --filter='clicks.click_table'
In `settings.toml` configuration looks like so:
```
[[crawlers]]
url = "postgresql://chrisriccomini@localhost/some_db"
filters = [
"events.page_*",
"clicks.click_table"
]
```
The filter format follows Unix shell-style wildcards as defined in Python [1]. The `fnmatch` pattern is matched against `<schema>.<format>` patterns as the crawler crawls.
[1] https://docs.python.org/3/library/fnmatch.html

Add `--filter` option to `recap refresh`

---

recap/cli.py
recap/crawlers/__init__.py
recap/crawlers/db/__init__.py
recap/crawlers/db/analyzers.py

I'm hooking up the other half of the analyzer implementation to `db.Crawler`. Prior to this change, the `DEFAULT_ANALYZER` param was hard coded for `db.Crawler`, so users couldn't set the analyzers they want to use. Now they can. use the `--analyzer` command:
```
pdm run recap refresh postgresql://chrisriccomini@localhost/some_db \
--analyzer=recap.crawlers.db.analyzers.TableColumnAnalyzer \
--analyzer=recap.crawlers.db.analyzers.TableAccessAnalyze
```
Users may also use the `settings.toml` file if they prefer:
```
[[crawlers]]
url = "postgresql://chrisriccomini@localhost/some_db"
analyzers = [
"recap.crawlers.db.analyzers.TableColumnAnalyzer",
"recap.crawlers.db.analyzers.TableAccessAnalyze"
]
```
I also took the opportunity to remove `TableDataProfilerAnalyzer` from the default analyzer …

Add `--analyzer` option to `recap refresh`

---

recap/cli.py
recap/plugins.py

Developers can now write plugins for Recap's CLI. Plugins are simply [Typer](https://typer.tiangolo.com/) apps, just like Recap's CLI.
To write a plugin, developers must define an entry-point in their project. Here's how it'd look in `pyproject.toml`:
```
[project.entry-points."recap.plugins.cli"]
hello-world = "recap.test:app"
```
`hello-world` defines the name of the command to be loaded into Recap. `recap.test:app` defines the module location and variabile name of the `typer.Typer` app. In this example, the `app` might be defined like so:
```
import typer
from rich import print
app = typer.Typer()
@app.command()
def hello_world_extension(name: str):
"""
A hello world test
"""
print(f'Hello, {name}!')
@app.command()
def goodbye_world_extension():
print('Goodbye, world!')
```
This …

Add CLI plugins

---

recap/cli.py
recap/crawlers/__init__.py
recap/plugins.py

Crawling sometimes takes a while. I've added a little `rich` SpinnerColumn and Progress task that spins while crawling is happening. When complete, a checkmark is displayed. I've also parsed out just the infra and instance name to avoid printing potentially sensitive information to the CLI (like usernames, passwords, and query params).
```
recap refresh postgresql://chrisriccomini@localhost/some_db
✓ Crawling postgresql://localhost ...
```

Add a nice spinner when crawling in the CLI

---

pdm.lock
pyproject.toml
recap/cli.py
recap/crawlers/db/analyzers.py
recap/crawlers/db/browser.py
recap/crawlers/db/crawler.py
recap/logging.py

Recap now has logging in the DB crawler and analyzer modules. I created a basic `logging.py` file with `setup_logging`, as well. `setup_logging` tries to load a Python dictionary from a .toml file using `tomli` [1]. The logging config should be in dictConfig format [2]. `setup_logging` looks in the `logging.config.path` config variable (or `RECAP_LOGGING__CONFIG__PATH` env var, I think) for the path to the logging config .toml file.
A default logging config is used when no `logging.config.path` is set. The default logging config is found in `logging.py`. It uses [RichHandler](https://rich.readthedocs.io/en/latest/logging.html), and sets a nicer timestamp format. It also configures the default log level to `INFO`. As a bonus, RichHandler also plays nicely with Rich's spinner console …

Add logging to Recap

---

pyproject.toml
recap/cli.py
recap/plugins/__init__.py
recap/plugins/commands/plugins.py

Add a simple `recap plugins` command that lists the current plugins. The command has four subcommands: `analyzers`, `browsers`, `catalogs`, and `commands`. Specifying one will list the plugins for that type.
```
recap plugins analyzers
[
"db.access",
"db.column",
"db.comment",
"db.foreign_key",
"db.index",
"db.location",
"db.primary_key",
"db.profile",
"db.view_definitions"
]
```

Add `recap plugins` command

---

README.md
docs/analyzers.md
docs/browsers.md
docs/catalogs.md
docs/commands.md
docs/configuration.md
docs/crawler.md
docs/index.md
docs/logging.md
docs/plugins.md
docs/quickstart.md
docs/server.md
mkdocs.yml
recap/plugins/catalogs/abstract.py
recap/plugins/catalogs/duckdb.py
recap/plugins/catalogs/fs.py

I've filled out the documentation a bit more. It's still very light, but I've at least added sections for all the main components in Recap. I still feel like a `concepts` section that explains Recap's directory and metadata structure is worth writing, but I'll save that for later.

Add expanded documentation

---

README.md
docs/index.md

I'm adding a link to my blog post, which explains I wrote Recap. Hopefully, this context will explain why yet-another-data-catalog is being forced upon the world.

Link README and docs to blog post

---

RELEASE.md

Recap's release is currently pretty manual. I want to get the process documented somewhere, so I don't forget it. I've put some instructions in the RELEASE.md for now.

Add release notes describing `pdm publish`

---

docs/quickstart.md
pdm.lock
pyproject.toml

@abhiramr pointed out that those without PostgreSQL drivers on their machine (specifically, libpq-dev) will have issues installing recap-core. PostgreSQL isn't actually required for Recap; it was included for convenience. Since it's causing problems, I'm going to remove it.
Users that wish to crawl PostgreSQL databases will now need to:
pip install psycopg2
Closes #75

Remove psycopg2 from dependencies

---

recap/plugins/catalogs/db.py
recap/plugins/commands/catalog.py

This is a half-way-done commit, but I don't want the PR to get too big. I've updated DatabaseCatalog to store all previous versions of metadata. I've also added a deleted_at tombstone to track deletions. Lastly, I added an optimization to the touch() method to skip parents once we discover a child already exists.
I haven't updated AbstractCatalog and the HTTP API to expose as_of yet.

Store versioned metadata in DatabaseCatalog

---

recap/analyzers/abstract.py
recap/analyzers/db.py
recap/browsers/abstract.py
recap/browsers/db.py
recap/crawler.py

I decided it's cleaner to optimistically call `open()` and catch exceptions if analyzers and browsers can't open a URL. The AbstractBrowser and AbstractAnalyzer classes are a bit simpler now.

Remove analyzable and browsable from analyzers and browsers

---

docs/plugins.md
docs/server.md
pdm.lock
pyproject.toml
recap/catalogs/recap.py
recap/commands/serve.py
recap/plugins.py
recap/routers/recap.py
recap/server.py

I've made Recap's FastAPI server pluggable. I also moved Recap's built-in HTTP endpoints to a plugin route called `recap`, which is exposed in the `recap.routers` entry-point in `pyproject.toml`.
As part of this change, I also changed the directory and metadata paths so they're not naked on the root. Directory paths now starts with `/directory` and metdata paths start with `/metadata`.
The docs have been updated as well.
Closes #53

Add FastAPI router plugins

---

docs/quickstart.md
pyproject.toml
recap/catalogs/abstract.py
recap/routers/recap.py

pipe operator all over, which was added in 3.10.  I would also like to use Python's pattern matching, which was added in 3.10. Excluding 3.9 will probably exclude some users, but frankly, they're so use to Python version abuse, they should be able to navigate this change.
Closes #88

Recap requires Python 3.10

---

pdm.lock
recap/browsers/abstract.py
recap/browsers/db.py

The `url` variable in AbstractBrowser was never actually used. DatabaseBrowser implemented it, but nothing calls it. I think it's left over from when I was experimenting on the browser API. I'm removing it.

Remove `url` from AbstractBrowser

---

pdm.lock
pyproject.toml
recap/analyzers/abstract.py
recap/analyzers/db/abstract.py
recap/analyzers/db/access.py
recap/analyzers/db/column.py
recap/analyzers/db/comment.py
recap/analyzers/db/foreign_key.py
recap/analyzers/db/index.py
recap/analyzers/db/location.py
recap/analyzers/db/primary_key.py
recap/analyzers/db/profile.py
recap/analyzers/db/view_definition.py
recap/crawler.py

Analyzers used to return `dict[str, Any]`; they now return `BaseModel | None`.
Thie `dict[str, Any]` return type never sat right with me. Analyzers can be used on their own in Python, so having a strong return type felt ergonomic. Strongly typed return types also make it possible to generate JSON schemas for the API--something I've been exploring.
I went back and forth between Python's `dataclasses.dataclass` and Pydantic's `BaseModel`. I opted for `BaseModel` for a number of reasons:
1. It serializes to JSON with `json()`, which is nice.
2. It has support for JSON schemas.
3. It has `__root__`, which allows metadata to be `Any`, rather than just a `dict`/`List`/`Tuple`.
4. Pydantic works nicely with FastAP and RichI
5. There were some other reasons, which I forget now. :P
I opted not to …

Return Pydantic `BaseModel` in analyzers

---

pdm.lock
pyproject.toml
recap/analyzers/db/abstract.py
recap/analyzers/db/location.py
recap/browsers/abstract.py
recap/browsers/db.py
recap/commands/crawl.py
recap/crawler.py
recap/paths.py

I'm moving away from unstructured `PurePosixPath` catalog directories. I like this change for two reasons:
1. Analyzers will be able to take kwargs instead of a PurePosixPath in `analyze()`. This will make analyzers more ergonomic for end users to call in Python.
2. `recap.routers.metadata` will be able to inspect all browsers to get the return types for `children`. This will allow the metadata `APIRouter` to expose strongly typed Pydantic models for all of the browser paths.
This change adds a `CatalogPath` Pydantic model. The `CatalogPath` defines template paths that represent a particular catalog path. The template paths use Starlette's simplified URI style [1]. For example:
/databases/{database}/instances/{instance}/schemas/{schema}/tables/{table}
Subtypes of `CatalogPath` can define …

Introduce `CatalogPath` model in `AbstractBrowser`

---

recap/analyzers/db/access.py
recap/analyzers/db/column.py
recap/analyzers/db/comment.py
recap/analyzers/db/foreign_key.py
recap/analyzers/db/index.py
recap/analyzers/db/location.py
recap/analyzers/db/primary_key.py
recap/analyzers/db/profile.py
recap/analyzers/db/view_definition.py
recap/crawler.py

Prior to this commit, `analyze()` methods had to include a `**` argument at the end to handle unused arguments that were passed in from the crawler. This felt clunky. I added a convenience method in the crawler that filters out arguments that don't match the analyzer's `analyze()` method signature.
The implementation is a bit brittle. It doesn't, for example, handle `analyze(..., **kwargs)`. It should just pass the full path dict in that case. It also doesn't allow `analyze()` to take in the path model if it wants (like `analyze(model=SomeCatalogPath)`). This is all future work.

Eliminate `**_` requirement for `analyzer.analyze()` methods

---

recap/analyzers/abstract.py
recap/analyzers/db/abstract.py
recap/analyzers/db/access.py
recap/analyzers/db/column.py
recap/analyzers/db/comment.py
recap/analyzers/db/foreign_key.py
recap/analyzers/db/index.py
recap/analyzers/db/location.py
recap/analyzers/db/primary_key.py
recap/analyzers/db/profile.py
recap/analyzers/db/view_definition.py
recap/crawler.py

After going down the rabbit hole with kwargs for `analyze()`, I've decided it's just too much magic for the value it adds. I'm making `analyze()` take a `CatalogPath` now; a slight twist on the original implementation, which took a `PurePosixPath`.
This implementation is less natural for humans calling they API--they must now create a CatalogPath. But it's more convenient for the crawler and REST API, and is far more typesafe. I'm going with it for now.

Update `analyze()` to take a `CatalogPath`

---

recap/browsers/db.py
recap/crawler.py
recap/paths.py

Catalog path had `templates` as a list of PurePosixPath. This annoyed me for two reasons:
1. I'm going to eliminate PurePosixPath from the API. It's typesafe but clunky. I'm going to use `str`'s instead. This is the first step.
2. Multiple templates didn't really work without a `path` variable, which I didn't want to add.
The idea behind having multiple templates was to allow a single `CatalogPath` object to be returned from different paths in the browser. I can't think of any good concrete examples of this, though, so I'm ditching it.
I didn't want to add a `path` variable to the `CatalogPath` because it felt like a dupe of the data contained in the Pydantic variables and template.

Simplify `CatalogPath`

---

recap/browsers/abstract.py
recap/browsers/db.py
recap/catalogs/abstract.py
recap/catalogs/db.py
recap/catalogs/recap.py
recap/commands/catalog.py
recap/crawler.py
recap/paths.py
recap/routers/directory.py
recap/routers/metadata.py

Exposing PurePosixPath in APIs is cumbersome, even though it's more typesafe than `str`. Given that `str` appears to be idiomatic in Python-land, I'm going to go with it. I still use PurePosixPath in a few spots to make sure paths are properly formatted, but I no longer expose it in the API at all.

Remove `PurePosixPath` from APIs

---

pdm.lock
pyproject.toml

The BigQuery SQLALchemy dialect does not support Python 3.11. To get to the most recent version, I had to peg Python for the whole project to 3.10. I don't think this is sustainable in the long term, so hopefully the dialect supports 3.11 when it's released.

Upgrade `sqlalchemy-bigquery` to 1.5.0

---

recap/analyzers/sqlalchemy/columns.py

The TableColumnAnalyzer was failing for BigQuery becasue it was forcibly fetching 'autoincrement' on each column. The BigQuery SQLAlchemy dialect doesn't return this key, and so a KeyError was thrown.

Make TableColumnAnalyzer `autoincrement` optional for BigQuery

---

recap/routers/catalog/typed.py
recap/routers/catalog/untyped.py

The REST API was, somewhat annoyingly, returning default, null, and unset fields for Pydantic models. I've updated it to exclude such fields; to leave the client to their own devices when handling unset variables. I suppose some clients may care about the difference between null and unset, but I'm going to leave that for another day.
Closes #120

Exclude default, none, and unset in REST API

---

docs/commands.md
docs/quickstart.md

I missed a couple of spots in the docs when updating analyzer keys. I also missed the search `json_extract` clause, which should contain `db.location`, not just `location`. Fixed those.

Add `sqlalchemy.*` to quickstart JSON

---

recap/catalogs/abstract.py
recap/catalogs/db.py
recap/catalogs/recap.py
recap/commands/catalog.py
recap/routers/catalog/typed.py
recap/routers/catalog/untyped.py

As per @criccomini #128 request, Have renamed the `as_of`  parameter name to `time` which seems more standard.

Renamed as_of to time

---

docs/analyzers.md
docs/commands.md
pyproject.toml
recap/commands/analyze.py

Users can now analyze metadata on a system directly, rather than fetching cached data from the Recap catalog:
```
recap analyze db.column \
postgresql://username@localhost/some_db \
/schema/public/tables/some_table
```
Closes #118

Add `recap analyze` command

---

recap/commands/catalog.py

This is a very minor follow-on fix to #130. I noticed the CLI still has `as-of` in a few spots; probably escaped the grep search.

Change `--as-of` and `-a` to `--time` and `-t` in CLI

---

docs/browsers.md
docs/commands.md
pyproject.toml
recap/commands/analyze.py
recap/commands/browse.py

Users can now browse a system's directory structure directly rather than fetching cached data from the Recap catalog:
recap browse postgresql://username@localhost/some_db/schemas
Closes #119

Add `recap browse` command

---

docs/browsers.md
docs/quickstart.md
pdm.lock
pyproject.toml
recap/browsers/abstract.py
recap/browsers/analyzing.py
recap/browsers/db.py
recap/browsers/fs.py
recap/crawler.py
recap/paths.py

Recap can now crawl filesystems and object stores! I've added a `FilesystemBrowser` that uses `fsspec` to implement the `AbstractBrowser` class. This worked pretty much as expcected, which is a good sign. The browser returns `DirectoryPath` and `FilePath` children.
I haven't implemented any file analyzers yet, so right now the crawler just creates the file sturcture in the data catalog. No metadata is yet inserted into the catalog. That's the next step.

Add a `FilesystemBrowser` with `fsspec`

---

recap/browsers/fs.py
recap/routers/catalog/typed.py

I discovered a couple of bugs that broke the server after `FilesystemBrowser` was added.
1. The `FilesystemBrowser.root()` method was returning a generic `CatalogPath`. It needs to return a specific subtype so that the server can `str()` it to get the HTTP path.
2. The `typed.py` code was still formatting CatalogPath templates using .format() rather than Starlette's URI format syntax. This broke with FilePath and DirectoryPath because they both have a `{path:path}` param in their path, which `.format()` doesn't understand.

Fix server bugs discovered from `FilesystemBrowser`

---

pdm.lock
pyproject.toml
recap/analyzers/duckdb/columns.py
recap/browsers/analyzing.py

Recap can now get DuckDB-formatted schemas for CSV, TSV, and Parquet files on local, HTTP(S), or S3 filesystems.
Longer-term, I think frictionless data might be preferable since it supports more input sources. Still, I wanted to add DuckDB anyway because I want to use it for data profiling for these data types.
For JSON, I'm thinking of using GenSON to auto-generate JSON schemas for JSON files. I also opened a frictionless ticket, in the hopes that they might support JSON schema inference as well:
https://github.com/frictionlessdata/framework/issues/1405
I did experiment with DuckDB JSON schema parsing, but I found it to be inadequate. It does work:
```
SELECT json_group_structure(json)
FROM read_json_objects('some.json');
```
But the format is pretty clunky.
In short, remaining TODOs:
1. …

Add DuckDB `FileColumnAnalyzer`s for CSV, TSV, and Parquet

---

pdm.lock
pyproject.toml
recap/analyzers/frictionless/columns.py
recap/browsers/analyzing.py

Recap can now get Frictionless-formatted schemas for CSV, TSV, and Parquet files on local, HTTP(S), or S3 filesystems.
I also opened a frictionless ticket, in the hopes that they might support JSON schema inference as well:
https://github.com/frictionlessdata/framework/issues/1405

Add Frictionless `FileColumnAnalyzer`s for CSV, TSV, and Parquet

---

recap/catalogs/db.py

Paths weren't being deleted as expected. It looks like the bug was caused by the `execution_options(synchronize_session=False))`. According to the docs:
>>>
False - don’t synchronize the session. This option is the most efficient and is reliable once the session is expired, which typically occurs after a commit(), or explicitly using expire_all(). Before the expiration, objects that were updated or deleted in the database may still remain in the session with stale values, which can lead to confusing results.
>>>
https://docs.sqlalchemy.org/en/14/orm/session_basics.html#selecting-a-synchronization-strategy
Since I wasn't committing, the deletion update was never written. Adding `session.commit()` seems to have fixed things.

Fix `DatabaseCatalog.rm()` bug

---

pdm.lock
pyproject.toml
recap/analyzers/duckdb/columns.py
recap/analyzers/frictionless/columns.py
recap/analyzers/genson/columns.py
recap/analyzers/pandas/profile.py
recap/routers/catalog/typed.py

JSON, CSV, TSV, and Parquet files now have a Pandas data profile analyzer for local filesystems, remote object stores (S3), and remote HTTP(S) locations. The profiler also runs against all SQLAlchemy compatible URLs, so `TablePath` and `ViewPath` locations are also analyzed with Pandas.
I also took the opportunity to fix a bug in the Frictionless, GenSON, and DuckDB columns.py analyzers, which were using forward reference types for their `create_analyzer` methods. Since these analyzers both had the same class name, the bug caused the plugins to all resolve to the first analyzer class that it saw. Thus, DuckDB's analyzer was returned for the Frictionless and GenSON analyzers as well.
Future work:
* And Pandas's `DataFrame.hist()` data to the profile.
* Add sampling support to the analyzer.

Add Pandas `profile.py` analyzer for JSON, CSV/TSV, and Parquet

---

pdm.lock
pyproject.toml
recap/analyzers/frictionless/columns.py
recap/analyzers/genson/columns.py
recap/analyzers/pandas/profile.py

Thanks to a tip from my Frictionless GH issue:
https://github.com/frictionlessdata/framework/issues/1405
I figured out how to `describe()` JSON files to infer their schemas. I've updated the Frictionless `columns.py` analyzer. I also added `jsonl` to the GenSON and Pandas analyzers.

Add JSON schema inference for Frictionless columns analyzer

---

recap/browsers/fs.py

Recap was improperly prefixing all FS paths with a `/` for its `base_path`. This was causing problems for nested directories with the `gcsfs` filesystem, which expects bucket paths to start with `bucket/path/to/some/file` rather than `/bucket/path/to/some/file`. I've verified that `gs://`, `file://`, and `/` filesystem URLs all work with nested sudirectories now.

Fix `FilesystemBrowser` directory list bug

---

docs/api-ref/recap.analyzers.md
docs/api-ref/recap.browsers.md
docs/api-ref/recap.catalogs.md
docs/api-ref/recap.crawler.md
docs/api-ref/recap.paths.md
docs/api-ref/recap.routers.md
mkdocs.yml
pdm.lock
pyproject.toml
recap/routers/catalog/untyped.py

I found a really slick mkdocstring plugin for mkdocs. The plugin autogenerates API reference documentation from docstrings.
https://mkdocstrings.github.io/usage/
https://mkdocstrings.github.io/python/usage/
I've set up the initial plugin.
Closes #144

Adding an API reference section to the docs

---

README.md
docs/index.md

Very minor update to point README and docs/index.md to the Python API. Since there's no index, I used the analyzers page.

Add README link to Python API

---

pdm.lock
pyproject.toml
recap/analyzers/bigquery/access.py
recap/crawler.py

Recap now gets BigQuery access information for views, tables, and datasets.
This analyzer is more complex that it should be, but BigQuery's access API is a mess. They've just introduced table-level access controls, which go through the `get_iam_policy` API rather than the `dataset.access_entries` attribute. BigQueryAccessAnalyzer munges these two data structures into a standard-ish format called `AccessEntry`. See the docs on the analyzer for more information.
And here's some documentation on Google's AccessEntry class for datasets (which is different from Recap's).
https://github.com/googleapis/python-bigquery/blob/bd1da9aa0a40b02b7d5409a0b094d8380e255c91/google/cloud/bigquery/dataset.py#L225
I also explored using `information_schema.object_privileges`, but it seems less efficient (and I …

Add BigQueryAccessAnalyzer for views, tables, and datasets

---

pyproject.toml

Now that I've added a meaningful feature (BigQueryAccessAnalyzer), it's time to bump the version.

Bumping to 0.4.1

---

pyproject.toml
recap/analyzers/bigquery/access.py
recap/analyzers/bigquery/job_counts.py
recap/analyzers/bigquery/latest_queries.py

Recap now analyzes BigQuery tables and views for job counts per-user and latest queries executed on the resource. This data is really useful for administrators and administrators trying to get usage info. It's also useful for discovery, since users need to know who is most likely to understand a table.

Add job counts and latest queries analyzers for BigQuery

---

recap/analyzers/bigquery/access.py
recap/analyzers/bigquery/job_counts.py
recap/analyzers/bigquery/latest_queries.py
recap/browsers/analyzing.py

The job count analyzer was querying the INFORMATION_SCHEMA.JOBS_BY_USER every time a new table was encountered. This was inefficient and potentially costly. I've added logic to query each region once, and cache all table counts for each dataset in the region. This speeds things up and drops costs. It does mean the analyzer now stores all job counts for all tables in memory, which could potentially be a lot of memory if a region has a ton of tables.
I also fixed a bug that was causing unprocessable entity errors. Turns out that empty access/query lists were being `.dict()`'d to `{}` if they were empty (rather than `{"__root__":[]})`. This was breaking verification. I removed the defaults, which seems to have fixed the problem.

Cache BigQuery job counts in BigQueryJobCountAnalyzer

---

pdm.lock
pyproject.toml
recap/integrations/bigquery.py
recap/integrations/fsspec.py
recap/integrations/sqlalchemy.py
recap/metadata.py
recap/schema/avro.py
recap/schema/bigquery.py
recap/schema/frictionless.py
recap/schema/json_schema.py
recap/schema/sqlalchemy.py
recap/schema/sqlglot.py

I've added a bunch of (rough) code for converting to and from Recap schemas.
Currently, you can convert from:
* Avro
* Parquet
* CSV/TSV
* JSON files and JSON schemas
* BigQuery
* SQLAlchemy DBs
To:
* JSON Schemas
* `create_table` DDL (using `sqlglot`)
Recap's schema structure is used as the intermediary.

Add `metadata.Schema` conversion for common serialization types

---

recap/catalog.py
recap/cli.py
recap/integrations/bigquery.py
recap/integrations/fsspec.py
recap/integrations/sqlalchemy.py
recap/repl.py
recap/schema/converters/avro.py
recap/schema/converters/bigquery.py
recap/schema/converters/frictionless.py
recap/schema/converters/json_schema.py
recap/schema/converters/sqlalchemy.py
recap/schema/converters/sqlglot.py
recap/schema/model.py
recap/server.py

I decided to eliminate the `metadata.py` file and move models into specific `model.py` files in their respective subdirectories. I want to start structuring Recap in a more modular way. This is a step in that direction.

Move `Schema` model into `recap.schema.model` module

---

README.md
docs/index.md
pdm.lock
pyproject.toml
recap/schema/converters/proto.py
tests/schema/converters/test_proto.py

I've added *very* basic support for `recap.schema` protocol buffer support. Users can now call `from_proto()` with a `google.proto.descript.Descriptor` and get a Recap schema in response. Many proto features are missing (enums and a lot more), but it's a start.

Add basic protobuf conversion support

---

recap/schema/converters/avro.py
recap/schema/converters/bigquery.py
recap/schema/converters/frictionless.py
recap/schema/converters/proto.py
recap/schema/converters/sqlalchemy.py
recap/schema/converters/sqlglot.py
recap/schema/types.py
tests/schema/converters/test_avro.py

I've refactored the schema base types (Int, Float, etc) to use bits instead of min/max as their constraint. Recap is now pretty much fully inline with Arrow's Scheam.fbs and developer types (time32, time64, etc).
I did this because I'm more interested in modeling physical types than logical ones. I care if a float is IEEE encoded vs. arbitrary-precision decimal, for example. It is just more relevant when converting between IDLs and DB schemas.

Move away from constraints on base types

---

recap/schema/converters/json_schema.py
recap/schema/converters/proto.py
recap/schema/converters/sdl.py
recap/schema/types.py
tests/schema/converters/test_proto.py
tests/schema/converters/test_sdl.py

I'm starting to codify the Recap type system into an object-based schema definition language.
By "object based", I mean it's using standard in-memory objects (dict, list, str, int, float) instead of a text-based SDL (think TOML, YAML, JSON, etc). It's agnostic to the SDL serialization format. It's also not directly using Recap's in-memory `Type` types because they are less human-friendly to write.
This is all laying the groundwork for a three tier architecture:
1. Recap types (`types.Bytes()`)
2. Recap in-memory schema objects (`{"type": "bytes", ...}`)
3. Recap serialized schema objects (TOML, JSON, YAML, etc)
The schema registry will use (3), probably with JSON.

Add a Recap schema definition language

---

SPEC.md
recap/schema/types.py
tests/schema/converters/test_sdl.py

I'm attempting to document Recap's type spec. The spec matches very closely to what I've implemented in Python.
The reason for documenting the spec now is that I want to express Recap schemas in the catalog API, which means it's going to get serialized as JSON (or whatever). I want to nail down what that looks like.

Add Recap type spec

---

SPEC.md

I've added a UUID derived type to the spec because it's a common enough type.
I also re-ordered the alias section to lead with the built-in's since I think they clarify the `alias` use case well.
Fixed some typos as well, and added some outside link references for Arrow and Avro.

Add UUID type to spec

---

SPEC.md

I decided to add a `nullable` to Recap's struct fields. This mirrors Arrow's `field` table in Schema.fbs, but moves Recap's type system away from Avro's null modeling (union with defaults). `nullable` is just too ergonomic for developers to ignore. Recap should support it even if it is just syntactic sugar.

Add `nullable` to Recap spec

---

SPEC.md
recap/schema/parser.py
recap/schema/types.py
recap/schema/types2.py
tests/schema/converters/test_sdl.py

The current type implementation is buggy and doesn't support type self-referencing. I've implemented a more robust version in types2.py that I believe supports true self-referencing (including nested self references). I have tested it manually, but haven't written unit tests, so I am not replacing types.py yet.
I also dropped Pydantic from types2.py in favor of dataclasses. My thinking here is to make the schema zero-dependency so it can be used in other libraries without causing trouble.
There are some minor updates to the spec, too. I removed `nullable` because it's a pain to implement right now. Maybe in the future I will re-add it. I also added support for bracketed union syntatic sugar (`"type": [null, "int32"]`).

Lay groundwork for robust types with self-reference support

---

recap/schema/diff.py
recap/schema/types.py

I had a really great description for this commut, but `vi` bombed out on me and it's getting late on a Friday. Suffice it to say, there's now a diff. Here's an example:
```
obj_a = {
"type": "struct",
"fields": [
{
"name": "field1",
"type": "int32",
},
{
"name": "field2",
"type": "int64",
},
],
}
obj_b = {
"type": "struct",
"fields": [
{
"name": "field1",
"type": "int64",
},
{
"name": "field2",
"type": "int64",
},
{
"name": "field3",
"type": "list",
"values": "string32",
},
],
}
```
The returned diff would be:
```
{'fields': {0: {'type': Diff(before='int32', after='int64')},
2: {'name': Diff(before=None, after='field3'),
'type': Diff(before=None, after='list'),
'values': Diff(before=None, after='string32')}}}
```
More to do: write tests, unify `diff` with `parse_obj` and `to_obj` (namely, …

Add a basic `diff` method to diff Recap types

---

recap/schema/__init__.py

I've added a helper that takes schema objects (Avro, Proto, etc) rather than Recap type objects. Internally, it still converts to Recap type objects to use with `recap.schema.diff`, but it's a little more convenient.

Add `diff` helper to `recap.schema`

---

pdm.lock
pyproject.toml
recap/readers/sqlalchemy.py

BigQuery's SQLAlchemy driver was blocking 3.11 support. They've updated their setup.py now, so Recap can support 3.12. I've updated the pyproject.toml accordingly.
I've also re-added BigQuery URLs to the sqlalchemy.py reader. I previously had a BigQuery reader, but I've removed it to simply things (for now). The converter still exists, but isn't being used.
Closes #195

Support Python 3.11

---

.github/workflows/ci.yaml
java/.gitignore
java/pom.xml
java/recap-core/pom.xml
java/recap-core/src/main/java/build/recap/Client.java
java/recap-core/src/main/java/build/recap/Data.java
java/recap-core/src/main/java/build/recap/Type.java
java/recap-core/src/test/java/build/recap/ClientTest.java
java/recap-core/src/test/java/build/recap/TypeTest.java
java/recap-kafka/pom.xml
java/recap-kafka/src/main/java/build/recap/kafka/Converter.java
java/recap-kafka/src/main/java/build/recap/kafka/logical/DateConverter.java
java/recap-kafka/src/main/java/build/recap/kafka/logical/DecimalConverter.java
java/recap-kafka/src/main/java/build/recap/kafka/logical/LogicalConverter.java
java/recap-kafka/src/main/java/build/recap/kafka/logical/TimeConverter.java
java/recap-kafka/src/main/java/build/recap/kafka/logical/TimestampConverter.java
java/recap-kafka/src/test/java/build/recap/kafka/ConverterTest.java

The library provides a `recap-core` library which contains Recap's type system and a client for the Recap catalog.
The `recap-kafka` library provides a bridge to Kafka Connect's `SchemaAndValue` class. Integration with KC unlocks a ton of functionality for Recap since KC already has Proto, Avro, and JSON Schema converters.
The Java code is really MVP, but I wanted to bring it into the main project now.

Add a Java library for Recap

---

python/recap/converters/recap.py
python/recap/types.py
python/tests/test_types.py

I added `logical` fields back to the spec while working on Recap's Java converters. I'm updating Python now to support the `logical` field so it's compatible with Recap Java and the spec.

Add logical support to Python types

---

pdm.lock
pyproject.toml

There were a ton of dependencies left over from previous Recap iterations. I've trimmed the dependencies down to only what's needed.

Remove legacy dependencies from `pyproject.toml`

---

.github/workflows/ci.yaml
pdm.lock
pyproject.toml
recap/readers/snowflake.py
tests/readers/test_postgresql.py
tests/readers/test_snowflake.py

SnowflakeReader now has a unit test. I'm using
[fakesnow](https://github.com/tekumara/fakesnow) to mock it. I've observed a number of oddities with fakesnow, and I'm not sure whether they're actually Snowflake oddities or not. The two main ones are:
1. Numeric precision seems to be 64, 32, 16, etc. The Snowflake docs say it should always be 38.
2. Varchars seem to be missing octet length.
I've opened issues for both of these:
https://github.com/tekumara/fakesnow/issues/11
https://github.com/tekumara/fakesnow/issues/12

Test SnowflakeReader

---

pdm.lock
pyproject.toml
recap/converters/avro.py
recap/converters/protobuf.py
tests/converters/test_protobuf.py

I've added a basic (and somewhat hacky) ProtobufConverter. The converter uses my [proto-schema-parser](https://github.com/criccomini/proto-schema-parser) library, which is based off of Buf.build's ANTLR4
[lexer and parser](https://github.com/bufbuild/protobuf.com/tree/main/examples/antlr) files.
The converter supports:
* All primitive types
* Message, Enum, `oneof`, and `map` types
* `repeated` fields
* Forward references
The converter does not support cyclic references, namespaces, or imports.
Closes #248

Add basic ProtobufConverter

---

recap/converters/avro.py
recap/converters/protobuf.py
recap/types.py
tests/converters/test_avro.py
tests/converters/test_protobuf.py
tests/test_types.py

A global singleton RecapType.type_registry was causing problems. Parsing schemas multiple times would cause type alias collisions if any type aliases matched.
I replaced the glocal registry with a RecapTypeRegistry class. The logic for tracking aliases is moved into the converters, where it makes more sense, I think. This allows different converters to handle aliases based on how proto/json/avro work.
The converters have been updated to use the new registry class.
Closes #253

Remove global type registry from RecapType

---

recap/converters/avro.py
recap/converters/protobuf.py
tests/converters/test_protobuf.py

I found a bug where deeply nested protobufs weren't getting resolved from their ProxyTypes. Fixing.

Support deeply nested messages in ProtobufConverter

---

recap/readers/confluent_registry.py
tests/integration/readers/test_confluent_registry.py
tests/unit/readers/test_confluent_registry.py

I've added "PROTOBUF" schema type support for the ConfluentRegistryReader. This is a basic implementation that doesn't support schema references.

Add ProtobufConverter support for ConfluentRegistryReader

---

recap/readers/confluent_registry.py
tests/integration/readers/test_confluent_registry.py
tests/unit/readers/test_confluent_registry.py

I've added "JSON" schema type support for the ConfluentRegistryReader. This is a basic implementation that doesn't support schema references.
Closes #249

Add JSONSchemaConverter support for ConfluentRegistryReader

---

recap/types.py
tests/unit/test_types.py

Small bug fix in the `from_dict()` method to handle union types defined as a list of type names
```
type: union
types: ["int32", "string32"]
```
Without this change the recursive call to `from_dict()` is passed a string and fails with
```
type_dict = 'int32', registry = <recap.types.RecapTypeRegistry object at 0x116a2d060>
def from_dict(
type_dict: dict[str, Any],
registry: RecapTypeRegistry | None = None,
) -> RecapType:
>       type_dict = type_dict.copy()
E       AttributeError: 'str' object has no attribute 'copy'
recap/types.py:298: AttributeError
```

from_dict() bug fix for union list shorthand

---

tests/unit/test_types.py

Minor cleanup of a test. Rather than looping, let's just parameterize it so we get better debugging on failure.

Parameterize test_union_type

---

recap/readers/hive_metastore.py
tests/integration/readers/test_hive_metastore.py
tests/unit/readers/test_hive_metastore.py

HiveMetadataReader now converts VOID columns to NullTypes.
Closes #282

Add VOID support for HiveMetadataReader

---

recap/converters/protobuf.py
tests/unit/converters/test_protobuf.py

I've added basic support for some well-known types.
The logical type mapping for timestamp and duration are somewhat lossy. The Protobuf WKTs support larger values than the `build.recap` logical types. I'm choosing to live with this for now, rather than introduce Protobuf logical types into Recap.
Closes #269

Add Timetsamp, Duration, and NullValue WKTs to ProtobufReader

---

recap/types.py
tests/unit/test_types.py

Based on discussions here:
* https://github.com/recap-build/recap/discussions/284
And a draft PR here:
* https://github.com/recap-build/recap/pull/292
I've decided that `string` and `bytes` types should defaulte `byte` length to 64 KiB when users haven't defined them in the concrete syntax tree (the YAML, TOML, JSON, etc).
See the disucssion and PR for more info.

Default `bytes` to 64KiB for StringType and BytesType

---

recap/converters/avro.py
recap/converters/protobuf.py
recap/types.py
tests/unit/converters/test_avro.py
tests/unit/test_types.py

Developers can now use `to_dict` to convert a RecapType (abstract syntax tree) to its corresponding dictionary representation (concrete syntax tree).
This feature will allow developers to serialize Recap types to JSON, YAML, TOML, etc.
`clean_dict` is a helper function that removes default values from a dictionary. It also does some minor compaction to make the output more idiomatic (e.g. simple union types are converted to lists).
```
{
"type": "union",
"types": [
{
"type": "int",
"alias": None,
"doc": None,
"logical": None,
"bits": 32,
"signed": true,
},
],
}
```
Becomes `[{ "type": "int", "bits": 32}]`.
`alias_dict` is a helper function that attempts to replace any types that match an alias with the alias name.
```
{
"type": "int",
"bits": 32,
"signed": true,
}
```
And:
```
{
"type": …
```

Add `to_dict`, `clean_dict`, and `alias_dict` to types.py

---

recap/readers/dbapi.py
recap/types.py
tests/unit/converters/test_json_schema.py

`make_nullable` was leaving `default` in the child type and was not setting `default=None` when no default was set.
I fixed this and also updated `DbapiReader` to use `make_nullable`.

Fix `make_nullable` bugs

---

recap/converters/protobuf.py
recap/types.py
tests/unit/test_types.py

String shorthand should be modeled in the concrete syntax tree (JSON, YAML, TOML, etc), not the abstract syntax tree (RecapTypes). The UnionType AST data model was allowing string types, though, whic is incongruent with this philosophy. I've removed `str` from `types: list[RecapType | str]`.
I also took the opportunity to rename some tests to make them a bit more explicit.
Closes #294

Remove `str` from UnionType `types` parameter

---

recap/converters/json_schema.py
recap/readers/dbapi.py
recap/types.py

Some more cleanup and refactoring. I decided to put `make_nullable` into RecapType as an instance method since it's working on a RecapType instance. Seemed to make more sense there.

Move `make_nullable` to RecapType instance method

---

recap/converters/avro.py
recap/converters/json_schema.py
recap/converters/protobuf.py
recap/readers/confluent_registry.py
recap/readers/dbapi.py
recap/readers/hive_metastore.py
tests/integration/readers/test_confluent_registry.py
tests/integration/readers/test_hive_metastore.py
tests/integration/readers/test_postgresql.py
tests/unit/converters/test_avro.py
tests/unit/converters/test_json_schema.py
tests/unit/converters/test_protobuf.py
tests/unit/readers/test_confluent_registry.py
tests/unit/readers/test_hive_metastore.py
tests/unit/readers/test_snowflake.py

I'm prepping to write converters from RecapTypes to Avro, Protobuf, and JSON. To make things clearer, I've renamed `struct` and `convert` to `to_recap` to make it more explicit. I'll add a `from_recap` for each of the converters next.

Rename `struct` and `convert` for readers and converters

---

recap/converters/avro.py
recap/types.py
tests/unit/converters/test_avro.py
tests/unit/test_types.py

RecapTypes that include ProxyType can now be converted to Avro.
Built-in aliases (int32, decimal256) are fully resolved rather than treated as aliases.
```
{"type": "int32"}
```
Converts to Avro as:
```
{"type": "int"}
```
But fully qualified aliases are converted to Avro `aliases` values.
```
{"type": "int", "bits": 32, "alias": "build.recap.Int32Thing"}
```
Converts to Avro as:
```
{"type": "int", "aliases": ["build.recap.Int32Thing"]}
```
Closes #305

Add `alias` support for `AvroConverter.from_recap`

---

pdm.lock
recap/readers/hive_metastore.py
tests/unit/readers/test_hive_metastore.py

Including pymetastore's stats in the `extra_attrs` dictionary for each supported type.
The included stats are:
```python
case (
LongTypeStats()
| DoubleTypeStats()
| DecimalTypeStats()
| DateTypeStats()
):
recap_type.extra_attrs |= {
"low": col_stats.stats.lowValue,
"high": col_stats.stats.highValue,
"cardinality": col_stats.stats.cardinality,
}
case StringTypeStats():
recap_type.extra_attrs |= {
"average_length": col_stats.stats.avgColLen,
"max_length": col_stats.stats.maxColLen,
"cardinality": col_stats.stats.cardinality,
}
case BooleanTypeStats():
recap_type.extra_attrs |= {
"true_count": col_stats.stats.numTrues,
"false_count": col_stats.stats.numFalses,
}
case BinaryTypeStats():
recap_type.extra_attrs |= {
"average_length": col_stats.stats.avgColLen,
"max_length": …
```

Include `stats` in HiveMetastoreReader when `include_stats` is set

---

recap/converters/avro.py
tests/unit/converters/test_avro.py

I noticed AvroConverter was missing `fixed` support for `to_recap`. Fixing that.
Closes #309

Add `fixed` type for `to_recap` in AvroConverter

---

pdm.lock
recap/readers/hive_metastore.py
tests/unit/readers/test_hive_metastore.py

The `pymetastore` was incorrectly handling date stats. I've upgraded the library and tweaked Recap's code to work with dates. I've also removed `ttypes.Decimal` stats support for now because I haven't had time to investigate the decimal binary (unscaled) format.

Update `pymetastore` to properly handle `date` stats

---

recap/converters/protobuf.py
tests/unit/converters/test_protobuf.py

I noticed that the ProtobufConverter didn't support messages in its values (e.g. `map<int32, SomeMessage>`). I fixed this.
I also took the opportunity to enforce int/string types for Proto maps since, "The key type can be any integral or string type." [1]
[1] https://protobuf.dev/reference/protobuf/proto3-spec/#map_field

Support `Message` types in ProtobufConverter

---

recap/converters/protobuf.py
tests/unit/converters/test_protobuf.py

Recap now supports type aliases for Protobufs. This works now:
```protobuf
syntax = "proto3";
message Outer {
message Inner {
int32 innerValue = 1;
}
Inner outerValue = 2;
}
```
All nested `Message` and `Enum` references are returned as `ProxyType`s.
Package spaces also work:
```protobuf
syntax = "proto3";
package foo.bar.baz;
message Outer {
message Inner {
int32 innerValue = 1;
}
Inner outerValue = 2;
}
```
This will generate `alias=foo.bar.baz.Outer` for the Outer Recap StructType.
If no package is specified, `_root` is used as the default package because Recap does not allow naked type aliases (they are reserved for built-in Recap types).
I also added tests for self-referencing/recursive types.

Support aliases in `ProtobufConverter.to_recap`

---

pdm.lock

I'm prepping for `from_recap` in the ProtobufConverter. I am thinking of returning the `ast` in that method. 0.3.0 makes it possible to serialize the ast back to a string if I want to.

Upgrade `proto-schema-parser` to 0.3.0

---

.github/workflows/ci.yaml
pdm.lock
pyproject.toml
recap/readers/bigquery.py
tests/integration/readers/test_bigquery.py

Recap can now convert BigQuery table schemas to Recap StructTypes.
Some notes:
1. Nested types are supported (RECORD, STRUCT)
2. Repeated/ARRAYs are supported
3. JSON types are treated as STRING
4. STRING and BYTES have a max length of 65KiB by default
For (4), I had a really hard time nailing down the exact max string size in BQ. [This](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types) page says they have a 2 byte header on strings/bytes, which I assume is to store the byte length. Thus I went with 65KiB.
I'm also using [bigquery-emulator](https://github.com/goccy/bigquery-emulator) to test. I've only included integration tests.
Closes #285

Add BigQueryReader.to_recap

---

.github/workflows/ci.yaml

Main started failing with some certi issues. Everything continued to work fine for me with PDM locally, so I decided to ditch `python3 -m ven venv` in the CI in favor of PDM's virtualenv management. This fixed the cert issues.

Replace `venv` with PDM's virtualenv management

---

recap/converters/avro.py
tests/unit/readers/test_snowflake.py

AvroConverter's from_recap method was not converting Recap floats to Avro doubles unless they were exactly 64 bits. All other Recap floats were treated as Avro floats even if their bits were > 64.

Handle oddly sized floats in AvroConverter.from_recap

---

pdm.lock
pyproject.toml

Fakesnow had some fixes, but I couldn't use it until:
https://github.com/tekumara/fakesnow/issues/16
Now that it's fixed and released, I'm upgrading.

Upgrade fakesnow

---

recap/types.py
tests/unit/test_types.py

Aliases currently include `doc` and `default` attributes when referenced.
```python
type: struct
fields:
- name: foo
alias: build.recap.Foo
type: string
default: some_default_string
- name: bar
type: build.recap.Foo
```
In this example, `bar` will also have a default of "some_default_string". This is not intuitive. This patch removes `doc` and `default` attributes when persisting alias types to the `RecapTypeRegistry`. Consequently, `bar` will no longer have a default. Explicit defaults in alias references will continue to work as expected:
```python
type: struct
fields:
- name: foo
alias: build.recap.Foo
type: string
- name: bar
type: build.recap.Foo
default: some_other_default
```
`bar` will have "some_other_default" as its default, regardless of what default is set (or not) for `foo`. …

Exclude `doc` and `default` from aliased types

---

pdm.lock
pyproject.toml
recap/converters/json_schema.py
recap/converters/protobuf.py
recap/types.py
tests/unit/converters/test_json_schema.py

JSON schemas can now convert `$ref`s to Recap aliases. The `$id` is used as the alias name, and a default `$id` to alias strategy is provided that converts something like `http://recap.build/linkedlist.schema.json` to an alias like `build.recap.linkedlist.schema.json`. See code for the rules.
The converter uses the [referencing](https://referencing.readthedocs.io/) library to track and fetch remote JSON schemas. By default, it uses `httpx`. A custom referencing [Registry](https://referencing.readthedocs.io/en/stable/api/#referencing.Registry) can be provided.
The implementation does not currently pay attention to $anchor, $defs, or $dynamicAnchor.
Closes #330

Add `$ref` and `$id` support for JSONSchemaConverter

---

recap/converters/json_schema.py
recap/types.py
tests/unit/converters/test_json_schema.py

`from_recap` converts RecapTypes to JSON schemas. It's very basic right now, but it works for simple use cases.
It's missing a ton of JSON schema functionality; things like dynamicAnchor, prefixItems, etc. It also doesn't pay attention to logical types.
What it does do is handle RecapType aliases. It defines aliases as $defs in the root of the document, and uses $ref to reference them. It also converts built-in aliases (like int32, uint64, decimal128, etc) to concrete types, rather than defining $defs for them.
Closes #331

Add `from_recap` to JSONSchemaConverter

---

recap/readers/postgresql.py

UUID is a very common type for columns in PostgreSQL ([docs](https://www.postgresql.org/docs/current/datatype-uuid.html)). We therefore want to support this type in the recap PostgreSQL reader.

Add UUID to Postgres recognized types

---

recap/types.py
tests/unit/test_types.py

I've added validation rules to each RecapType that needs to be validated. The rules are all according to the [0.2.0](https://recap.build/specs/type) spec. These rules are run when `from_dict` is called.
Closes #362

Add `validate` methods for each RecapType

---

recap/converters/json_schema.py
tests/unit/converters/test_json_schema.py

The `JSONSchemaConverter` now converts string types to `BytesType` if `"format": "bytes"` is set for the JSON schema string type.
BytesTypes are created with a LONG_MAX length because JSON schema imposes no max.
Closes #345

Add `format: bytes` support for JSONSchemaConverter.to_recap

---

README.md

The format table was linking to serde/system pages. It should link to recap.build for SEO.

Link README.md to recap.build

---

tests/unit/converters/test_json_schema.py

I got a little nervous that I might be generating malformed JSON schemas in the tests, so I added `check_schema` calls to the `jsonschema` library to validate that all JSON schemas we generate and/or test against are actually valid. Good news is all the tests pass!

Add JSON schema metaschema validation
